SCREEN_W = 220
SCREEN_H = 176
FPS = 30

COL_BLACK = 0
COL_NAVY = 1
COL_PURPLE = 2
COL_GREEN = 3
COL_BROWN = 4
COL_DARKBLUE = 5
COL_LIGHTBLUE = 6
COL_WHITE = 7
COL_RED = 8
COL_ORANGE = 9
COL_YELLOW = 10
COL_LIME = 11
COL_CYAN = 12
COL_GRAY = 13
COL_PINK = 14
COL_PEACH = 15

ATTR_RED = 0
ATTR_BLUE = 1
ATTR_GREEN = 2
ATTR_YELLOW = 3
ATTR_PURPLE = 4
NUM_ATTRS = 5
ATTR_COLORS = [COL_RED, COL_DARKBLUE, COL_LIME, COL_YELLOW, COL_PURPLE]
ATTR_NAMES = ["RED", "BLUE", "GREEN", "YELLOW", "PURPLE"]

STATE_TITLE = 0
STATE_GARAGE = 1
STATE_GACHA = 2
STATE_RACE_SELECT = 3
STATE_RACE = 4
STATE_RESULT = 5

RACE_PHASE_INTRO = 0
RACE_PHASE_PUZZLE = 1
RACE_PHASE_BOARD = 2
RACE_PHASE_DUEL = 3
RACE_PHASE_FINISH = 4

GRID_COLS = 6
GRID_ROWS = 5
CELL_SIZE = 18
GRID_PIXEL_W = GRID_COLS * CELL_SIZE
GRID_PIXEL_H = GRID_ROWS * CELL_SIZE
GRID_X = (SCREEN_W - GRID_PIXEL_W) // 2
GRID_Y = 74
MATCH_MIN = 3
MAX_CASCADE_STEPS = 6
TURN_TIME_LIMIT_FRAMES = 150
INTRO_FRAMES = 45

BASE_ADVANCE = 2
MOMENTUM_ADVANCE = 1
CHARGE_PER_GROUP = 25
CHARGE_MAX = 100
CURRENCY_PER_GROUP = 8

MAX_TURNS = 30
NUM_RIVALS = 3
NUM_RACERS = NUM_RIVALS + 1
DUEL_TRIGGER_RANGE = 3
DUEL_COOLDOWN_TURNS = 2
STUN_TURNS = 1
RIVAL_BASE_ADVANCE = 2.0
REFERENCE_SPEED = 12.0

ARENA_W = 160
ARENA_H = 120
ARENA_X = (SCREEN_W - ARENA_W) // 2
ARENA_Y = (SCREEN_H - ARENA_H) // 2
TOKEN_RADIUS = 8
DUEL_MAX_ROUNDS = 3
MAX_ROUND_FRAMES = 90
MAX_CHARGE_FRAMES = 45
MAX_LAUNCH_SPEED = 6.0
FRICTION = 0.985
WALL_RESTITUTION = 0.9
COLLISION_RESTITUTION = 0.8
DAMAGE_PER_SPEED = 4.0
HP_BASE = 100.0
HP_PER_POWER = 5.0
DUEL_WIN_ADVANCE = 4
DUEL_LOSE_RETREAT = 2
AIM_TURN_RATE = 0.05
SETTLE_SPEED = 0.05

GACHA_COST = 150
GACHA_TABLE = [(1, 0.45), (2, 0.30), (3, 0.17), (4, 0.06), (5, 0.02)]

LEVEL_CAP = 20
SUB_STAT_BONUS = 0.2

STARTER_CURRENCY = 300
STARTER_TEMPLATE_ID = "novice_red"

DEBUG = False
